name: 'Publish NuGet'
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PROJECT_FILE_PATH: aspnetcore-fux-dns.csproj
          PACKAGE_NAME: Fux.Dns
